# Generated by Django 3.2.9 on 2021-11-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('math', 'คณิตศาสตร์'), ('science', 'วิทยาศาสตร์'), ('art', 'ศิลปะ'), ('eng', 'ภาษาอังกฤษ')], default='NULL', max_length=50)),
                ('std_name', models.CharField(max_length=100)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
    ]
